# Generated by Django 3.2.9 on 2021-11-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.CharField(max_length=56, null=True),
        ),
    ]
