# Generated by Django 3.2.9 on 2021-12-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snotes', '0002_auto_20211128_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
