# Generated by Django 3.2.9 on 2022-02-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snotes', '0003_auto_20211204_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
